name: kaaru_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.4
  formz: ^0.8.0
  freezed_annotation: ^3.0.0
  go_router: ^16.0.0
  google_fonts: ^6.3.0
  image_picker: ^1.1.2
  json_annotation: ^4.9.0
  retrofit: ^4.6.0
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2

dev_dependencies:
  build_runner: ^2.5.4
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  retrofit_generator: ^9.7.0

flutter:
  uses-material-design: true
